services:
  acct-manager:
    build: .
    networks:
      - account-net
    volumes:
      - accounts:/home/.ethereum/goerli/keystore
    tty: true
    stdin_open: true
    ports:
      - "8080"
networks:
  account-net:
volumes:
  accounts:
